In [2]:
x = 3
y = 4
print(x+y)

7


In [1]:
import pandas as pd

Numpy
First created by Jim Hugunin   
only similar type of data we store in array.   
array is 50x faster than python list

In [14]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)
arr2 = np.array([1,2,3,4,5],float) # type of each number inside of the list given by second argument.
print("Second array",arr2)
print("print the type of array\n",type(arr))
##array can be multidimentional
arr2=np.array([[1,2,3],[4,5,6]],float)
print("two dimentiaonl array:\n",arr2)
print("first element of first column\n",arr2[0,0])
print("second element of first column:\n",arr2[0,1]) #element of frst row and second column
print(arr2[1,1]) #element of second row and second column
print(arr2[1,2]) #element of second row and third column 

[1 2 3 4 5]
Second array [1. 2. 3. 4. 5.]
print the type of array
 <class 'numpy.ndarray'>
two dimentiaonl array:
 [[1. 2. 3.]
 [4. 5. 6.]]
first element of first column
 1.0
second element of first column:
 2.0
5.0


In [23]:
##Array elements are accessed, sliced and manipulated just like list.
a = np.array([1,4,5,7.5],float)
print(a[:2]) # slicing first two elments of array.
print(a[3:]) # slicing last element of array
print(a[-1:]) # slicing last element
print(a[3:5])
print(a[3:4])

[1. 4.]
[7.5]
[7.5]
[7.5]
[7.5]
[1. 4. 5.]


In [84]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # we give list as rows of array
print(b)
###slicing
print(b[2,2]) # element third row and third column
print(b[0]) # printing frist row to the 2D matrix
print(b[:1])
print(b[:2])
print("columns")
print(b[:,2])
print(b[:,[1,2]])
print("Shape of the matrix\n",b.shape)
print("data type of the matrix",b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[1 2 3]
[[1 2 3]]
[[1 2 3]
 [4 5 6]]
columns
[3 6 9]
[[2 3]
 [5 6]
 [8 9]]
Shape of the matrix
 (3, 3)
data type of the matrix int32


In [79]:
# find an element in array
100 in b
c= np.array(range(10)) #one dimentional array using range
print(c)
print(c.shape)
#convert one dimention to two dimention array
c = c.reshape((5,2)) #using reshape function covert one dimention to two dimention.
print(c)
print("after reshaping to two dimention the shape is:",c.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
after reshaping to two dimention the shape is: (5, 2)


In [87]:
a = np.array([4,5,6],float)
b = a 
c = a.copy() # copying before change of first element.
print(a)
print(b)
print(c)
a[0]=1
print(a)
print(b)
print(c)

[4. 5. 6.]
[4. 5. 6.]
[4. 5. 6.]
[1. 5. 6.]
[1. 5. 6.]
[4. 5. 6.]


In [89]:
## Create a list from arra
a =np.array([10,20,30],float)
print(a)
a =a.tolist() # convert array to list
print(a) # list is comma seperated

[10. 20. 30.]
[10.0, 20.0, 30.0]


In [92]:
#convert raw dat into binary
a =np.array([10,20,30],float)
print(a)
b= a.tostring() #convert to string
print(b)
c=np.frombuffer(b) #what is frombuffer? taking binary to convert to numbers
print(c)

[10. 20. 30.]
b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x004@\x00\x00\x00\x00\x00\x00>@'
[10. 20. 30.]


In [95]:
##Transpose of the matrix
a = np.array([[10,20,30,40],[40,50,60,70]])
print(a) ##matrix shape 2 X 4
c = a.transpose()
print(c) ## matrix shape 4 X 2

[[10 20 30 40]
 [40 50 60 70]]
[[10 40]
 [20 50]
 [30 60]
 [40 70]]


In [96]:
##matrix 
a = np.array([[10,20,30,40],[40,50,60,70]])
print(a)
b = a.flatten()
print(b) # flatten converts two dimention to one

[[10 20 30 40]
 [40 50 60 70]]
[10 20 30 40 40 50 60 70]


In [100]:
# others ways of creating arrays
np.arange(6,dtype=int)
#zeros and ones
np.zeros(10,dtype=float)
np.ones((2,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [103]:
a = np.array([[1,2,3],[2,3,4]],float)
np.ones_like(a)
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
##identity matrix is square matrix having diagonals equal to one
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [109]:
np.eye(4,k=2,dtype=int)
np.eye(4,k=-2,dtype=int)
np.eye(6,k=2,dtype=int)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [116]:
##array arithmetic
a=np.array([1,2,3]) #individual elements of one dimentional array
b=np.array([5,6,7])
pirnt(a+b)
print(b-a)
print(a*b)


array([ 5, 12, 21])